// RUN: rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:gfx906 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin | FileCheck %s --check-prefix=ARCH
// RUN: rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:gfx908:sramecc+ --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin | FileCheck %s --check-prefix=ARCH_SRAMECC
// RUN: rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:gfx908:sramecc+:xnack- --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin | FileCheck %s --check-prefix=ARCH_SRAMECC_XNACK
// RUN: rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:gfx90a:sramecc+:xnack- --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin | FileCheck %s --check-prefix=90A_SRAMECC_XNACK
// RUN: ! rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:gfx908:x --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin
// RUN: ! rocmlir-lib-test --args " --operation conv --arch amdgcn-amd-amdhsa:aa --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv_nchw_kcyx_nkhw --groupsize 1" --option bin

// ARCH: ELF
// ARCH_SRAMECC: ELF
// ARCH_SRAMECC_XNACK: ELF
// 90A_SRAMECC_XNACK: ELF
