////////////////////////////////////////////
// Test case which depends on 1 GPU kernel.
////////////////////////////////////////////

// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name foo --groupsize 1" --option kernelcount | FileCheck %s --check-prefix=KERNELCOUNT1
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name foo --groupsize 1" --option bin | FileCheck %s --check-prefix=BIN1
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name foo --groupsize 1 --kernel_id 0" --option tuningparams | FileCheck %s --check-prefix=TUNING1
// RUN: rocmlir-gen --conv-config "--operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name foo --groupsize 1 " | FileCheck %s --check-prefix=DRIVER1

// KERNELCOUNT1: Kernel count=1
// BIN1: ELF
// TUNING1: globalSize{{.*}}localSize{{.*}}
// DRIVER1: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 0 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [1, 1]} : memref<1x1024x1024x1x1xf32>, memref<64x1x1024x14x14xf32>, memref<64x1x1024x14x14xf32>

////////////////////////////////////////////
// Test case which depends on 4 GPU kernels.
////////////////////////////////////////////

// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1" --option kernelcount | FileCheck %s --check-prefix=KERNELCOUNT4
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1" --option bin | FileCheck %s --check-prefix=BIN4
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1 --kernel_id 0" --option tuningparams | FileCheck %s --check-prefix=TUNING4_0
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1 --kernel_id 1" --option tuningparams | FileCheck %s --check-prefix=TUNING4_1
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1 --kernel_id 2" --option tuningparams | FileCheck %s --check-prefix=TUNING4_2
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1 --kernel_id 3" --option tuningparams | FileCheck %s --check-prefix=TUNING4_3
// RUN: rocmlir-gen --conv-config " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 6 --out_w 6 --fil_h 3 --fil_w 3 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name bar --groupsize 1 " | FileCheck %s --check-prefix=DRIVER4

// KERNELCOUNT4: Kernel count=4
// BIN4: ELF
// BIN4: ELF
// BIN4: ELF
// BIN4: ELF
// TUNING4_0: globalSize{{.*}}localSize{{.*}}
// TUNING4_1: globalSize{{.*}}localSize{{.*}}
// TUNING4_2: globalSize{{.*}}localSize{{.*}}
// TUNING4_3: globalSize{{.*}}localSize{{.*}}
// DRIVER4: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 0 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [2, 2]} : memref<1x1024x1024x3x3xf32>, memref<64x1x1024x14x14xf32>, memref<64x1x1024x6x6xf32>
// DRIVER4: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 1 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [2, 2]} : memref<1x1024x1024x3x3xf32>, memref<64x1x1024x14x14xf32>, memref<64x1x1024x6x6xf32>
// DRIVER4: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 2 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [2, 2]} : memref<1x1024x1024x3x3xf32>, memref<64x1x1024x14x14xf32>, memref<64x1x1024x6x6xf32>
// DRIVER4: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 3 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [2, 2]} : memref<1x1024x1024x3x3xf32>, memref<64x1x1024x14x14xf32>, memref<64x1x1024x6x6xf32>

////////////////////////////////////////////
// Test case which depends on 2 GPU kernels,
// with the 1st being the zero initialization.
////////////////////////////////////////////
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name baz --groupsize 1 " --option kernelcount | FileCheck %s --check-prefix=KERNELCOUNT2
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name baz --groupsize 1 " --option bin | FileCheck %s --check-prefix=BIN2
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name baz --groupsize 1 --kernel_id 0" --option tuningparams | FileCheck %s --check-prefix=TUNING2_0
// RUN: rocmlir-lib-test --args " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name baz --groupsize 1 --kernel_id 1" --option tuningparams | FileCheck %s --check-prefix=TUNING2_1
// RUN: rocmlir-gen --conv-config " --operation conv2d_bwd_data --arch amdgcn-amd-amdhsa:gfx906 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2 --conv_stride_w 2 --padding_h 0 --padding_w 0 --kernel_name baz --groupsize 1 " | FileCheck %s --check-prefix=DRIVER2

// KERNELCOUNT2: Kernel count=2
// BIN2: ELF
// BIN2: ELF
// TUNING2_0: globalSize=100352, localSize=64
// TUNING2_1: globalSize{{.*}}localSize{{.*}}
// DRIVER2: rock.init_kernel %arg1 features =  dot : memref<256x1x1024x14x14xf32>
// DRIVER2: rock.conv2d_bwd_data(%arg0, %arg1, %arg2) features = dot {arch = "amdgcn-amd-amdhsa:gfx906", dilations = [1, 1], filter_layout = ["g", "k", "c", "y", "x"], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernelId = 0 : index, numCU = 64 : i32, output_layout = ["no", "go", "ko", "ho", "wo"], padding = [0, 0, 0, 0], strides = [2, 2]} : memref<1x2048x1024x1x1xf32>, memref<256x1x1024x14x14xf32>, memref<256x1x2048x7x7xf32>
