#!/usr/bin/env perl
use 5.030;
use strict;
use warnings;

# This is menat to run from the build directory to generate the list of
# dependencies needed for the fat librockCompiler.

# It should be run from the build directory on Linux.

my @rocmlirLibs;
my @mlirLibs;

my @deps = split /\n/,`ninja -t query lib/libMLIRRockThin.a`;
not $? or die "failed to get target dependencies";

foreach (@deps) {
  last if /outputs:/;
  if (m#external/llvm-project/llvm/lib/lib(\w+)\.a#) {
    push @mlirLibs, $1;
  } elsif (m#lib/lib(\w+)\.a#) {
    push @rocmlirLibs, $1;
  }
}
@mlirLibs = sort @mlirLibs;
@rocmlirLibs = sort @rocmlirLibs;

print "### DO NOT EDIT!\n";
print "### Generated by mlir/utils/jenkins/static-checks/get_fat_library_deps_list.pl\n";
print "set(__mlir_libs\n";
# While querying the executable makes this work in the shared library build
# it introduces duplicates.
my $prev = "";
foreach my $lib (@mlirLibs) {
  print "$lib\n" if $prev ne $lib;
  $prev = $lib;
}
print ")\n";
$prev = "";
print "set(__rocmlir_libs\n";
foreach my $lib (@rocmlirLibs) {
  print "$lib\n" if $prev ne $lib;
  $prev = $lib;
}
print ")\n";
