#!/usr/bin/env perl
use 5.030;
use strict;
use warnings;

# This is menat to run from the build directory to generate the list of
# dependencies needed for the fat librockCompiler.

# It should be run from the build directory on Linux.

# Libraries that must NOT be bundled into librockCompiler.a, even if they
# appear in the dependency graph of MLIRRockThin. They are shipped as
# separate shared libraries on purpose -- bundling them would re-introduce
# the very dependencies the fat-lib split is meant to keep out.
#
#   mlir_rocm_arch_runtime: link-depends on libamdhip64 / libamd_comgr /
#       ROCm's libLLVM.so. MLIRRockOps loads it on demand via dlmopen so the
#       fat archive stays free of those transitive dependencies.
#       See mlir/lib/ExecutionEngine/RocmArchRuntime.cpp.
#   conv-validation-wrappers: a runner-only helper not consumed by
#       downstream compile-time consumers (MIOpen, MIGraphX). Excluded from
#       all-static fat-build mode via EXCLUDE_FROM_ALL ${BUILD_FAT_LIBROCKCOMPILER}.
my %excludedLibs = map { $_ => 1 } qw(
  mlir_rocm_arch_runtime
  conv-validation-wrappers
);

my @rocmlirLibs;
my @mlirLibs;

my @deps = split /\n/,`ninja -t query lib/libMLIRRockThin.a`;
not $? or die "failed to get target dependencies";

foreach (@deps) {
  last if /outputs:/;
  if (m#external/llvm-project/llvm/lib/lib(\w+)\.a#) {
    push @mlirLibs, $1 unless $excludedLibs{$1};
  } elsif (m#lib/lib(\w+)\.a#) {
    push @rocmlirLibs, $1 unless $excludedLibs{$1};
  }
}
@mlirLibs = sort @mlirLibs;
@rocmlirLibs = sort @rocmlirLibs;

print "### DO NOT EDIT!\n";
print "### Generated by mlir/utils/jenkins/static-checks/get_fat_library_deps_list.pl\n";
print "set(__mlir_libs\n";
# While querying the executable makes this work in the shared library build
# it introduces duplicates.
my $prev = "";
foreach my $lib (@mlirLibs) {
  print "$lib\n" if $prev ne $lib;
  $prev = $lib;
}
print ")\n";
$prev = "";
print "set(__rocmlir_libs\n";
foreach my $lib (@rocmlirLibs) {
  print "$lib\n" if $prev ne $lib;
  $prev = $lib;
}
print ")\n";
