import os
import sys
import argparse

import pulp
import numpy as np
import re
import glob
import pandas as pd


class FileWriter():
    """
    A class to handle updating quick-tuning perfcofigs file.
    """

    def __init__(self, pargs):
        self.op = pargs.op
        self.arch = pargs.arch

    def parse_perfconfigs(self, perfconfig_str):
        """
        Parses a perfconfigs in expected input format
        """
        perfconfig_str = perfconfig_str.replace('v3:', '')
        config_values = perfconfig_str.split(',')
        total_values = len(config_values)
        converted_values = []
        for idx, value in enumerate(config_values):
            if idx > total_values - 3 and total_values == 11:
                if value == '1':
                    converted_values.append('true')
                else:
                    converted_values.append('false')
            else:
                converted_values.append(value)

        formated_perfconfig = ','.join(converted_values)
        return formated_perfconfig

    def replace_section(self, file_path, ifdef_guard, begin_marker, end_marker, new_content):
        """
        Replaces a section between the markers with new content
        """
        with open(file_path, 'r') as file:
            content = file.read()

        pattern = re.compile(f'{re.escape(begin_marker)}.*?{re.escape(end_marker)}', re.DOTALL)
        if not pattern.search(content):
            ifdef_match = re.search(rf'{re.escape(ifdef_guard)}(.*?)(?=#endif)', content, re.DOTALL)
            if (ifdef_match):
                insert_pos = ifdef_match.end()
                content = content[:insert_pos] + f'{begin_marker}\n\n{end_marker}\n\n' + content[
                    insert_pos:]
            else:
                raise ValueError(f"Cannot find {ifdef_guard} in {file_path}")

        replacement = f'{begin_marker}\n{new_content}\n{end_marker}'
        content = pattern.sub(replacement, content)

        with open(file_path, 'w') as file:
            file.write(content)

    def update_lookup_table(self, file_path, ifdef_guard, mapping):
        """
        Updates a lookup table in the file with the given mapping
        """
        with open(file_path, 'r') as file:
            content = file.read()

        pattern = re.compile(f'{re.escape(mapping)}', re.DOTALL)
        if not pattern.search(content):
            ifdef_match = re.search(rf'{re.escape(ifdef_guard)}(.*?)(?=#endif)', content, re.DOTALL)
            if (ifdef_match):
                insert_pos = ifdef_match.end()
                content = content[:insert_pos] + f'{mapping}\n\n' + content[insert_pos:]
            else:
                raise ValueError(f"Cannot find {ifdef_guard} in {file_path}")

            with open(file_path, 'w') as file:
                file.write(content)

    def is_accel(self, arch, datatype):
        instruction_type = self.get_instruction_type(arch, datatype)
        if instruction_type == "XDL" or instruction_type == "Wmma":
            return True
        else:
            return False

    def get_instruction_type(self, arch, datatype):
        """
        Determines the instruction type based on architecture and data type
        """
        if arch.startswith("gfx9"):
            return "XDL"
        elif arch.startswith("gfx1") and datatype != "f32":
            return "Wmma"
        else:
            return "NonAccel"

    def init_inc_file(self, file_path):
        """
        Initialize an .inc file with predefined structure
        """
        instruction_types = ["NonAccel", "XDL", "Wmma"]

        with open(file_path, 'w') as file:
            file.write("// THIS IS AN AUTOGENERATED FILE.\n")
            file.write("// DO NOT EDIT THIS FILE DIRECTLY!\n\n")
            file.write("// clang-format off\n")
            for instruction_type in instruction_types:
                file.write(f"#ifdef {instruction_type}_DEFINITIONS_GEN\n\n#endif\n\n")
                file.write(f"#ifdef {instruction_type}_DECLARATIONS_GEN\n\n#endif\n\n")

            file.write("#ifdef NonAccel_LOOKUP_TABLE_GEN\n\n#endif\n\n")
            file.write("#ifdef Accel_LOOKUP_TABLE_GEN\n\n#endif\n\n")

    def get_init_params_names(self, arch, dtype, op):
        """
        Helper method to generate init_params and n_init_params names.
        """
        if dtype == 'f32':
            init_params = "initParameters"
        elif dtype == 'f16':
            init_params = "initParametersFp16"
        elif dtype == 'fp8' and op == 'conv':
            init_params = "initParametersForwardFp8"
        elif dtype == 'fp8' and op == 'gemm':
            init_params = "initParametersFp8"
        elif dtype == 'i8' and op == 'conv':
            init_params = "initParametersForwardI8"
        elif dtype == 'i8' and op == 'gemm':
            init_params = "initParametersI8"
        else:
            raise ValueError(f"Unsupported dtype: {dtype}")

        init_params = f"{init_params}{op.capitalize()}{arch.capitalize()}"
        n_init_params = f"n{init_params[0].upper()}{init_params[1:]}"

        return init_params, n_init_params

    def get_init_params_definitions(self, arch, dtype, op):
        """
        Generates initialization parameter definitions for a given data type and operation.
        """
        accel_type = 'Accel' if self.is_accel(arch, dtype) else 'NonAccel'
        instruction_type = self.get_instruction_type(arch, dtype)

        init_params, n_init_params = self.get_init_params_names(arch, dtype, op)

        if dtype == 'f32' and not self.is_accel(arch, dtype):
            instruction_type = ''

        return f"const InitParams{accel_type} PopulateParams{instruction_type}::{init_params}[PopulateParams{instruction_type}::{n_init_params}]"

    def get_init_params_declaration(self, arch, dtype, op):
        """
        Generates initialization parameter declarations for a given data type and operation.
        """
        accel_type = 'Accel' if self.is_accel(arch, dtype) else 'NonAccel'

        init_params, n_init_params = self.get_init_params_names(arch, dtype, op)

        return (f"static const InitParams{accel_type} {init_params}[{n_init_params}]",
                f"static constexpr size_t {n_init_params}")

    def update_config_file(self, result):
        """
        Updates the configuration file with selected perfconfigs
        """
        file_path = "../../../include/mlir/Dialect/Rock/Tuning/QuickTuningPerfconfigs.inc"
        if not os.path.exists(file_path):
            self.init_inc_file(file_path)

        datatype_names_defs = {
            'f32': self.get_init_params_definitions(self.arch, 'f32', self.op),
            'f16': self.get_init_params_definitions(self.arch, 'f16', self.op),
            'fp8': self.get_init_params_definitions(self.arch, 'fp8', self.op),
            'i8': self.get_init_params_definitions(self.arch, 'i8', self.op)
        }

        for datatype, perfconfigs in result.items():
            lines = []
            datatype_name = datatype_names_defs.get(datatype)
            lines.append(f"{datatype_name} = {{")
            for idx, perfconfig in enumerate(perfconfigs):
                formated_perfconfig = self.parse_perfconfigs(perfconfig)
                if idx == len(perfconfigs) - 1:
                    lines.append(f"    {{{formated_perfconfig}}}")
                else:
                    lines.append(f"    {{{formated_perfconfig}}},")
            lines.append("};")

            instruction_type = self.get_instruction_type(self.arch, datatype)
            new_content = '\n'.join(lines)
            self.replace_section(
                file_path, f"#ifdef {instruction_type}_DEFINITIONS_GEN",
                f"// BEGIN_{self.op.upper()}_{instruction_type}_{datatype}_{self.arch}_DEFS",
                f"// END_{self.op.upper()}_{instruction_type}_{datatype}_{self.arch}_DEFS",
                new_content)

        datatype_names_decs = {}
        datatype_n_decs = {}

        for dtype in ['f32', 'f16', 'fp8', 'i8']:
            init_params_dec, n_params_dec = self.get_init_params_declaration(
                self.arch, dtype, self.op)
            datatype_names_decs[dtype] = init_params_dec
            datatype_n_decs[dtype] = n_params_dec

        for datatype, perfconfigs in result.items():
            lines = []
            datatype_name_dec = datatype_names_decs.get(datatype)
            datatype_n_dec = datatype_n_decs.get(datatype)
            lines.append(f"{datatype_n_dec} = {len(perfconfigs)};")
            lines.append(f"{datatype_name_dec};")

            instruction_type = self.get_instruction_type(self.arch, datatype)
            new_content = '\n'.join(lines)
            self.replace_section(
                file_path, f"#ifdef {instruction_type}_DECLARATIONS_GEN",
                f"// BEGIN_{self.op.upper()}_{instruction_type}_{datatype}_{self.arch}_DECS",
                f"// END_{self.op.upper()}_{instruction_type}_{datatype}_{self.arch}_DECS",
                new_content)

        for datatype in result:
            instruction_type = self.get_instruction_type(self.arch, datatype)
            class_prefix = f"PopulateParams{instruction_type}" if self.is_accel(
                self.arch, datatype) else "PopulateParams"
            init_params, n_init_params = self.get_init_params_names(self.arch, datatype,
                                                                    self.op.lower())
            key = f'"{self.arch}_{self.op.lower()}_{datatype}"'
            value = f'{{{class_prefix}::{init_params}, {class_prefix}::{n_init_params}}}'
            self.update_lookup_table(
                file_path, "#ifdef Accel_LOOKUP_TABLE_GEN" if self.is_accel(self.arch, datatype)
                else "#ifdef NonAccel_LOOKUP_TABLE_GEN", f'{{{key}, {value}}},')


class PerfConfigsFinder():
    """
    A class to find optimal perfconfigs based on input data
    """

    def __init__(self, combined_data, pargs):
        self.th = pargs.th
        self.op = pargs.op
        self.input_dir = pargs.input_dir
        self.arch = pargs.arch
        self.df = combined_data

    def get_unique_perfconfigs_list(self, problems_to_perfconfigs):
        """
        Return a unique list of perfconfigs from the provided dictonary
        """
        perfconfigs_set = set()
        for perfconfigs_lists in problems_to_perfconfigs.values():
            perfconfigs_set.update(perfconfigs_lists)
        return list(perfconfigs_set)

    def get_top_n_perfconfigs_per_problems(self, df, target_columns):
        """
        Identifies the top perfconfigs for each problem based on a threshold
        """
        grouped = df.groupby(target_columns)
        problem_df = {}
        for name, grouped_df in grouped:
            max_value = grouped_df['TFlops'].max()
            threshold = max_value * self.th
            problem_df[name] = grouped_df[grouped_df['TFlops'] >= threshold]['PerfConfig']
        return problem_df

    def find(self):
        """
        Finds the minimal set of perfconfigs that cover all
        problems using set cover optimizaiton.
        Returns : A dictionary containing data types as keys and their
                  corresponding selected perfconfigs.
        """
        result = {}
        unique_data_types = self.df['DataType'].unique()

        target_columns = []
        if self.op == "gemm":
            target_columns = ['Chip', 'TransA', 'TransB', 'G', 'M', 'K', 'N']
        else:
            target_columns = [
                'Chip', 'Direction', 'InputLayout', 'N', 'C', 'H', 'W', 'K', 'Y', 'X', 'DilationH',
                'DilationW', 'StrideH', 'StrideW', 'PaddingH', 'PaddingW'
            ]

        for data_type in unique_data_types:
            df_typed = self.df[self.df['DataType'] == data_type]
            problems_to_perfconfigs = self.get_top_n_perfconfigs_per_problems(
                df_typed, target_columns)

            problems = problems_to_perfconfigs.keys()
            perfconfigs = self.get_unique_perfconfigs_list(problems_to_perfconfigs)

            n = len(problems)
            m = len(perfconfigs)

            perfconfig_to_index = {perfconfig: idx for idx, perfconfig in enumerate(perfconfigs)}

            # Create coverage matrix
            a = np.zeros((n, m), dtype=int)
            for i, problem in enumerate(problems):
                for perfconfig in problems_to_perfconfigs[problem]:
                    j = perfconfig_to_index[perfconfig]
                    a[i][j] = 1

            # Linear programming model to minimize the number of perfconfigs
            prob = pulp.LpProblem("SetCoverProblems", pulp.LpMinimize)
            x = pulp.LpVariable.dicts("x", range(m), cat='Binary')
            # Set up objective function to minimize the sum of selected perfconfigs
            prob += pulp.lpSum([x[j]] for j in range(m))
            for i in range(n):
                # Add a constraint for each problem ensuring at least one perfconfig is selected
                prob += pulp.lpSum([a[i][j] * x[j] for j in range(m)]) >= 1, f"Cover_problem_{i}"

            prob.solve(pulp.PULP_CBC_CMD(msg=0))

            selected_configs = [perfconfigs[j] for j in range(m) if x[j].varValue == 1]

            # Determine the number of problems covered by each selected perfcofing
            coverege_counts = {config: 0 for config in selected_configs}
            for i in range(n):
                for j in range(m):
                    if a[i][j] == 1 and x[j].varValue == 1:
                        coverege_counts[perfconfigs[j]] += 1

            # Sort selected perfconfigs by the number of problem they cover
            sorted_configs = sorted(selected_configs,
                                    key=lambda config: coverege_counts[config],
                                    reverse=True)

            result[data_type] = sorted_configs

        return result


def combine_data(input_dir, no_splitk):
    """
    Combine all *.debug tuning data into a single file.
    """
    tsv_files = glob.glob(os.path.join(input_dir, "*.debug"))

    dfs = []
    for file in tsv_files:
        df = pd.read_csv(file, sep='\t', index_col=None)
        dfs.append(df)
    if not dfs:
        return None
    new_df = pd.concat(dfs, ignore_index=True)

    # Remove splitK from tuning data
    if no_splitk:
        df_filtered = new_df[new_df['PerfConfig'].str.split(',').str[6] == '1']
        new_df = df_filtered

    return new_df


def print_results(result):
    """
    Print selected perfconfigs for each data type.
    """
    for datatype, perfconfings in result.items():
        print(f"Datatype: {datatype}")
        for idx, perfconfig in enumerate(perfconfings):
            print(f" {idx + 1}: {perfconfig}")


def main(args=None):
    """
    usage: quickTunerGen.py [-h] --input-dir INPUT_DIR --op {gemm,conv} [--th TH] --arch ARCH [--update] [--no-splitk]
    usage example: python3 quickTuningGen.py --input-dir tunedData --op conv --arch gfx90a --update --no-splitk
    """
    if args is None:
        args = sys.argv[1:]

    parser = argparse.ArgumentParser(prog='quickTunerGen.py')

    parser.add_argument('--input-dir', required=True, type=str)

    parser.add_argument('--op', required=True, type=str, choices=["gemm", "conv"])

    parser.add_argument("--th", required=False, type=float, default=0.93)

    parser.add_argument("--arch", required=True, type=str)

    parser.add_argument("--update", required=False, default=False, action='store_true')

    parser.add_argument('--no-splitk',
                        default=False,
                        action='store_true',
                        help='Remove the Split-K factor from the generated list')

    pargs = parser.parse_args()

    combined_data = combine_data(pargs.input_dir, pargs.no_splitk)

    finder = PerfConfigsFinder(combined_data, pargs)
    result = finder.find()

    print_results(result)

    file_writer = FileWriter(pargs)
    if pargs.update:
        file_writer.update_config_file(result)


if __name__ == '__main__':
    main(sys.argv[1:])
