// RUN: mlir-opt  %s  |FileCheck %s --check-prefix=CHECK
// RUN: mlir-opt  %s -miopen-affine-transform -miopen-affix-params -miopen-lowering-step2 -miopen-lowering-step3|FileCheck %s --check-prefix=CHECK_STEP3
module  {
func @miopen_test_limit(%arg0: memref<1x32x32x3x3xf32>, %arg1: memref<32x1x32x14x14xf32>, %arg2: memref<32x1x32x14x14xf32>) attributes {kernel = 0 : i32} {
    %0 = miopen.transform(%arg0) {bound_check = [1 : i32, 0 : i32, 0 : i32, 0 : i32, 0 : i32], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["g"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["g"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["k"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["k"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["c"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["c"], transformation = "PassThrough"}, {upper_layer_dimensions = [3 : i32, 4 : i32], upper_layer_names = ["ydot", "ytilda"], parameters = [1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [3 : i32], lower_layer_names = ["y"], transformation = "Embed"}, {upper_layer_dimensions = [5 : i32, 6 : i32], upper_layer_names = ["xdot", "xtilda"], parameters = [1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [4 : i32], lower_layer_names = ["x"], transformation = "Embed"}], upper_layer_layout = ["g", "k", "c", "ydot", "ytilda", "xdot", "xtilda"], lower_layer_layout = ["g", "k", "c", "y", "x"]} : memref<1x32x32x3x3xf32> to memref<1x32x32x3x1x3x1xf32>
    %1 = miopen.transform(%0) {lower_layer_layout = ["g", "k", "c", "ydot", "ytilda", "xdot", "xtilda"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["g"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["g"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["k"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["k"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["c"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["c"], transformation = "PassThrough"}, {begins = [0 : i32, 0 : i32], upper_layer_dimensions = [3 : i32, 5 : i32], ends = [3 : i32, 3 : i32], upper_layer_names = ["ydotslice", "xdotslice"], lower_layer_dimensions = [3 : i32, 5 : i32], lower_layer_names = ["ydot", "xdot"], transformation = "Slice"}, {begins = [0 : i32, 0 : i32], upper_layer_dimensions = [4 : i32, 6 : i32], ends = [1 : i32, 1 : i32], upper_layer_names = ["ytildaslice", "xtildaslice"], lower_layer_dimensions = [4 : i32, 6 : i32], lower_layer_names = ["ytilda", "xtilda"], transformation = "Slice"}], upper_layer_layout = ["g", "k", "c", "ydotslice", "ytildaslice", "xdotslice", "xtildaslice"]} : memref<1x32x32x3x1x3x1xf32> to memref<1x32x32x3x1x3x1xf32>
    %2 = miopen.transform(%1) {bound_check = [0 : i32, 0 : i32, 0 : i32, 0 : i32, 1 : i32], gridwise_gemm_argument_position = 0 : i32, lower_layer_layout = ["g", "k", "c", "ydotslice", "ytildaslice", "xdotslice", "xtildaslice"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gemmG"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["g"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["gemmK"], lower_layer_dimensions = [1 : i32, 3 : i32, 5 : i32], lower_layer_names = ["k", "ydotslice", "xdotslice"], transformation = "Merge"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["gemmM"], lower_layer_dimensions = [2 : i32, 4 : i32, 6 : i32], lower_layer_names = ["c", "ytildaslice", "xtildaslice"], transformation = "Merge"}], upper_layer_layout = ["gemmG", "gemmK", "gemmM"]} : memref<1x32x32x3x1x3x1xf32> to memref<1x288x32xf32>
    %3 = miopen.transform(%arg1) {layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gi"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["gi"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["ni"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["ni"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["ci"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["ci"], transformation = "PassThrough"}, {upper_layer_dimensions = [3 : i32, 4 : i32], upper_layer_names = ["hipad", "wipad"], parameters = [1 : i32, 1 : i32, 1 : i32, 1 : i32], lower_layer_dimensions = [3 : i32, 4 : i32], lower_layer_names = ["hi", "wi"], transformation = "Pad"}], upper_layer_layout = ["gi", "ni", "ci", "hipad", "wipad"], lower_layer_layout = ["ni", "gi", "ci", "hi", "wi"]} : memref<32x1x32x14x14xf32> to memref<1x32x32x16x16xf32>
    %4 = miopen.transform(%3) {lower_layer_layout = ["gi", "ni", "ci", "hipad", "wipad"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gi"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["gi"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["ni"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["ni"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["ci"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["ci"], transformation = "PassThrough"}, {upper_layer_dimensions = [3 : i32, 4 : i32], upper_layer_names = ["ytilda", "htilda"], parameters = [1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [3 : i32], lower_layer_names = ["hipad"], transformation = "Embed"}, {upper_layer_dimensions = [5 : i32, 6 : i32], upper_layer_names = ["xtilda", "wtilda"], parameters = [1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [4 : i32], lower_layer_names = ["wipad"], transformation = "Embed"}], upper_layer_layout = ["gi", "ni", "ci", "ytilda", "htilda", "xtilda", "wtilda"]} : memref<1x32x32x16x16xf32> to memref<1x32x32x1x16x1x16xf32>
    %5 = miopen.transform(%4) {lower_layer_layout = ["gi", "ni", "ci", "ytilda", "htilda", "xtilda", "wtilda"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gi"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["gi"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["ni"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["ni"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["ci"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["ci"], transformation = "PassThrough"}, {begins = [0 : i32, 0 : i32], upper_layer_dimensions = [3 : i32, 5 : i32], ends = [1 : i32, 1 : i32], upper_layer_names = ["ytildaslice", "xtildaslice"], lower_layer_dimensions = [3 : i32, 5 : i32], lower_layer_names = ["ytilda", "xtilda"], transformation = "Slice"}, {begins = [1 : i32, 1 : i32], upper_layer_dimensions = [4 : i32, 6 : i32], ends = [15 : i32, 15 : i32], upper_layer_names = ["htildaslice", "wtildaslice"], lower_layer_dimensions = [4 : i32, 6 : i32], lower_layer_names = ["htilda", "wtilda"], transformation = "Slice"}], upper_layer_layout = ["gi", "ni", "ci", "ytildaslice", "htildaslice", "xtildaslice", "wtildaslice"]} : memref<1x32x32x1x16x1x16xf32> to memref<1x32x32x1x14x1x14xf32>
    %6 = miopen.transform(%5) {bound_check = [0 : i32, 0 : i32, 0 : i32, 1 : i32, 0 : i32],gridwise_gemm_argument_position = 2 : i32, lower_layer_layout = ["gi", "ni", "ci", "ytildaslice", "htildaslice", "xtildaslice", "wtildaslice"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gemmG"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["gi"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["gemmM"], lower_layer_dimensions = [2 : i32, 3 : i32, 5 : i32], lower_layer_names = ["ci", "ytildaslice", "xtildaslice"], transformation = "Merge"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["gemmN"], lower_layer_dimensions = [1 : i32, 4 : i32, 6 : i32], lower_layer_names = ["ni", "htildaslice", "wtildaslice"], transformation = "Merge"}], upper_layer_layout = ["gemmG", "gemmM", "gemmN"]} : memref<1x32x32x1x14x1x14xf32> to memref<1x32x6272xf32>
    %7 = miopen.transform(%arg2) {layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["go"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["go"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["no"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["no"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["ko"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["ko"], transformation = "PassThrough"}, {upper_layer_dimensions = [3 : i32, 4 : i32], upper_layer_names = ["ydot", "htilda"], parameters = [-1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [3 : i32], lower_layer_names = ["ho"], transformation = "Embed"}, {upper_layer_dimensions = [5 : i32, 6 : i32], upper_layer_names = ["xdot", "wtilda"], parameters = [-1 : i32, 1 : i32, 0 : i32], lower_layer_dimensions = [4 : i32], lower_layer_names = ["wo"], transformation = "Embed"}], upper_layer_layout = ["go", "no", "ko", "ydot", "htilda", "xdot", "wtilda"], lower_layer_layout = ["no", "go", "ko", "ho", "wo"]} : memref<32x1x32x14x14xf32> to memref<1x32x32x3x16x3x16xf32>
    %8 = miopen.transform(%7) {lower_layer_layout = ["go", "no", "ko", "ydot", "htilda", "xdot", "wtilda"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["go"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["go"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["no"], lower_layer_dimensions = [1 : i32], lower_layer_names = ["no"], transformation = "PassThrough"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["ko"], lower_layer_dimensions = [2 : i32], lower_layer_names = ["ko"], transformation = "PassThrough"}, {begins = [0 : i32, 0 : i32], upper_layer_dimensions = [3 : i32, 5 : i32], ends = [3 : i32, 3 : i32], upper_layer_names = ["ydotslice", "xdotslice"], lower_layer_dimensions = [3 : i32, 5 : i32], lower_layer_names = ["ydot", "xdot"], transformation = "Slice"}, {begins = [1 : i32, 1 : i32], upper_layer_dimensions = [4 : i32, 6 : i32], ends = [15 : i32, 15 : i32], upper_layer_names = ["htildaslice", "wtildaslice"], lower_layer_dimensions = [4 : i32, 6 : i32], lower_layer_names = ["htilda", "wtilda"], transformation = "Slice"}], upper_layer_layout = ["go", "no", "ko", "ydotslice", "htildaslice", "xdotslice", "wtildaslice"]} : memref<1x32x32x3x16x3x16xf32> to memref<1x32x32x3x14x3x14xf32>
    %9 = miopen.transform(%8) {bound_check = [0 : i32, 0 : i32, 1 : i32, 0 : i32, 0 : i32], gridwise_gemm_argument_position = 1 : i32, lower_layer_layout = ["go", "no", "ko", "ydotslice", "htildaslice", "xdotslice", "wtildaslice"], layout = [{upper_layer_dimensions = [0 : i32], upper_layer_names = ["gemmG"], lower_layer_dimensions = [0 : i32], lower_layer_names = ["go"], transformation = "PassThrough"}, {upper_layer_dimensions = [1 : i32], upper_layer_names = ["gemmK"], lower_layer_dimensions = [2 : i32, 3 : i32, 5 : i32], lower_layer_names = ["ko", "ydotslice", "xdotslice"], transformation = "Merge"}, {upper_layer_dimensions = [2 : i32], upper_layer_names = ["gemmN"], lower_layer_dimensions = [1 : i32, 4 : i32, 6 : i32], lower_layer_names = ["no", "htildaslice", "wtildaslice"], transformation = "Merge"}], upper_layer_layout = ["gemmG", "gemmK", "gemmN"]} : memref<1x32x32x3x14x3x14xf32> to memref<1x288x6272xf32>
    miopen.gridwise_gemm(%2, %9, %6) {arch = "gfx906", dilations = [1 : i32, 1 : i32], filter_dimension = [1, 32, 32, 3, 3], filter_layout = ["g", "k", "c", "y", "x"], input_dimension = [32, 1, 32, 14, 14], input_layout = ["ni", "gi", "ci", "hi", "wi"], kernel_algorithm = "backward_data_v4r1", num_cu = 64 : i32, output_dimension = [32, 1, 32, 14, 14], output_layout = ["no", "go", "ko", "ho", "wo"], padding = [[1 : i32, 1 : i32], [1 : i32, 1 : i32]], strides = [1 : i32, 1 : i32]} : memref<1x288x32xf32>, memref<1x288x6272xf32>, memref<1x32x6272xf32>
    return
  }
// CHECK: bound_check = [1 : i32, 0 : i32, 0 : i32, 0 : i32, 0 : i32]
// CHECK: bound_check = [0 : i32, 0 : i32, 0 : i32, 0 : i32, 1 : i32]
// CHECK: bound_check = [0 : i32, 0 : i32, 0 : i32, 1 : i32, 0 : i32]
// CHECK: bound_check = [0 : i32, 0 : i32, 1 : i32, 0 : i32, 0 : i32]
// CHECK_STEP3: {{.*bound_check = \[1 : i32, 0 : i32, 0 : i32, 0 : i32, 1 : i32\].*metadata.*operand = 0.*}}
// CHECK_STEP3: {{.*bound_check = \[0 : i32, 0 : i32, 1 : i32, 0 : i32, 0 : i32\].*metadata.*operand = 0.*}}
// CHECK_STEP3: {{.*bound_check = \[0 : i32, 0 : i32, 0 : i32, 1 : i32, 0 : i32\].*metadata.*operand = 1.*}}
}
