# .pre-commit-config.yaml
# Run on all python files except those under external/

default_stages: [commit]

exclude: '^external/llvm-project/.*'

repos:
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        name: yapf (format Python)
        args: ["-i"]
