// RUN: rocmlir-gen -fut mlir_gemm_gemm --arch %arch --clone-harness %s | rocmlir-driver -kernel-pipeline=migraphx,highlevel -host-pipeline=migraphx,highlevel | rocmlir-gen -RMS_threshold 0.01 -ph -rand 1 -rand_min -1 -rand_max 1 -rand_type float -fut mlir_gemm_gemm_wrapper --verifier clone - | rocmlir-driver -host-pipeline mhal -kernel-pipeline full | xmir-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%conv_validation_wrapper_library_dir/libconv-validation-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext,%linalg_test_lib_dir/libmlir_float16_utils%shlibext,%linalg_test_lib_dir/libmlir_c_runner_utils%shlibext,%linalg_test_lib_dir/libmlir_async_runtime%shlibext --entry-point-result=void | FileCheck %s
// RUN: rocmlir-gen -fut mlir_gemm_gemm --arch %arch --clone-harness %s | rocmlir-driver -kernel-pipeline=migraphx-linalg,highlevel -host-pipeline=migraphx-linalg,highlevel | rocmlir-gen -RMS_threshold 0.01 -ph -rand 1 -rand_min -1 -rand_max 1 -rand_type float -fut mlir_gemm_gemm_wrapper --verifier clone - | rocmlir-driver -host-pipeline mhal -kernel-pipeline full | xmir-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%conv_validation_wrapper_library_dir/libconv-validation-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext,%linalg_test_lib_dir/libmlir_float16_utils%shlibext,%linalg_test_lib_dir/libmlir_c_runner_utils%shlibext,%linalg_test_lib_dir/libmlir_async_runtime%shlibext --entry-point-result=void | FileCheck %s
// CHECK: [1 1 1]
module {
  func.func @mlir_gemm_gemm(%arg0: !migraphx.shaped<1x64x64xbf16, 4096x64x1>, %arg1: !migraphx.shaped<1x64x64xbf16, 4096x64x1>, %arg2: !migraphx.shaped<1x64x64xbf16, 4096x64x1>) -> (!migraphx.shaped<1x64x64xbf16, 4096x64x1>) {
    %0 = migraphx.dot %arg0, %arg1 : !migraphx.shaped<1x64x64xbf16, 4096x64x1>, !migraphx.shaped<1x64x64xbf16, 4096x64x1> -> !migraphx.shaped<1x64x64xbf16, 4096x64x1>
    %1 = migraphx.dot %0, %arg2 {perf_config="attn:v2:64,128,32,16,32,16,4,4,1,2,1"} : !migraphx.shaped<1x64x64xbf16, 4096x64x1>, !migraphx.shaped<1x64x64xbf16, 4096x64x1> -> !migraphx.shaped<1x64x64xbf16, 4096x64x1>
    return %1 : !migraphx.shaped<1x64x64xbf16, 4096x64x1>
  }
}
