// RUN: rocmlir-opt --mlir-print-local-scope -rock-gridwise-gemm-to-blockwise -rock-blockwise-load-tile-to-threadwise %s | FileCheck %s

// CHECK-LABEL: @rock_gemm
func.func @rock_gemm(%arg0: memref<2359296xf16>, %arg1: memref<2359296xf16>, %arg2: memref<3145728xf16>) attributes {block_size = 256 : i32, grid_size = 192 : i32, kernel, arch = "gfx942"} {
  %0 = rock.transform %arg2 by <affine_map<(d0, d1, d2) -> ((d0 * 1024 + d1) * 1024 + d2)> by [<Unmerge{3, 1024, 1024} ["g", "m", "n"] at [0, 1, 2] -> ["raw"] at [0]>] bounds = [3, 1024, 1024] -> [3145728]> : memref<3145728xf16> to memref<3x1024x1024xf16>
  %1 = rock.transform %arg0 by <affine_map<(d0, d1, d2, d3, d4, d5) -> (((((d0 * 8 + d1) * 24 + d2) * 4 + d3) * 128 + d4) * 8 + d5)> by [<Unmerge{3, 8, 24, 4, 128, 8} ["g", "m", "k", "kPackPerBlock", "mPerBlock", "kPack"] at [0, 1, 2, 3, 4, 5] -> ["raw"] at [0]>] bounds = [3, 8, 24, 4, 128, 8] -> [2359296]> : memref<2359296xf16> to memref<3x8x24x4x128x8xf16>
  %2 = rock.transform %1 by <affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4, d2, d5)> by [<PassThrough ["g", "m", "mPerBlock", "k", "kPackPerBlock", "kPack"] at [0, 1, 2, 3, 4, 5] -> ["g", "m", "mPerBlock", "k", "kPackPerBlock", "kPack"] at [0, 1, 4, 2, 3, 5]>] bounds = [3, 8, 128, 24, 4, 8] -> [3, 8, 24, 4, 128, 8]> : memref<3x8x24x4x128x8xf16> to memref<3x8x128x24x4x8xf16>
  %3 = rock.transform %2 by <affine_map<(d0, d1, d2) -> (d0, d1 floordiv 128, d1 mod 128, d2 floordiv 32, (d2 mod 32) floordiv 8, d2 mod 8)> by [<PassThrough ["g"] at [0] -> ["g"] at [0]>, <Merge{8, 128} ["m"] at [1] -> ["m", "mPerBlock"] at [1, 2]>, <Merge{24, 4, 8} ["k"] at [2] -> ["k", "kPackPerBlock", "kPack"] at [3, 4, 5]>] bounds = [3, 1024, 768] -> [3, 8, 128, 24, 4, 8]> : memref<3x8x128x24x4x8xf16> to memref<3x1024x768xf16>
  %4 = rock.transform %arg1 by <affine_map<(d0, d1, d2, d3, d4, d5) -> (((((d0 * 8 + d1) * 24 + d2) * 4 + d3) * 128 + d4) * 8 + d5)> by [<Unmerge{3, 8, 24, 4, 128, 8} ["g", "n", "k", "kPackPerBlock", "nPerBlock", "kPack"] at [0, 1, 2, 3, 4, 5] -> ["raw"] at [0]>] bounds = [3, 8, 24, 4, 128, 8] -> [2359296]> : memref<2359296xf16> to memref<3x8x24x4x128x8xf16>
  %5 = rock.transform %4 by <affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4, d2, d5)> by [<PassThrough ["g", "n", "nPerBlock", "k", "kPackPerBlock", "kPack"] at [0, 1, 2, 3, 4, 5] -> ["g", "n", "nPerBlock", "k", "kPackPerBlock", "kPack"] at [0, 1, 4, 2, 3, 5]>] bounds = [3, 8, 128, 24, 4, 8] -> [3, 8, 24, 4, 128, 8]> : memref<3x8x24x4x128x8xf16> to memref<3x8x128x24x4x8xf16>
  %6 = rock.transform %5 by <affine_map<(d0, d1, d2) -> (d0, d1 floordiv 128, d1 mod 128, d2 floordiv 32, (d2 mod 32) floordiv 8, d2 mod 8)> by [<PassThrough ["g"] at [0] -> ["g"] at [0]>, <Merge{8, 128} ["n"] at [1] -> ["n", "nPerBlock"] at [1, 2]>, <Merge{24, 4, 8} ["k"] at [2] -> ["k", "kPackPerBlock", "kPack"] at [3, 4, 5]>] bounds = [3, 1024, 768] -> [3, 8, 128, 24, 4, 8]> : memref<3x8x128x24x4x8xf16> to memref<3x1024x768xf16>
  %7 = rock.transform %3 by <affine_map<(d0, d1, d2) -> (d0, d2, d1)> by [<PassThrough ["gemmG"] at [0] -> ["gemmG"] at [0]>, <PassThrough ["gemmK", "gemmM"] at [1, 2] -> ["gemmK", "gemmM"] at [2, 1]>] bounds = [3, 768, 1024] -> [3, 1024, 768]> : memref<3x1024x768xf16> to memref<3x768x1024xf16>
  %8 = rock.transform %6 by <affine_map<(d0, d1, d2) -> (d0, d2, d1)> by [<PassThrough ["gemmG"] at [0] -> ["gemmG"] at [0]>, <PassThrough ["gemmK", "gemmN"] at [1, 2] -> ["gemmK", "gemmN"] at [2, 1]>] bounds = [3, 768, 1024] -> [3, 1024, 768]> : memref<3x1024x768xf16> to memref<3x768x1024xf16>
  %alloc = memref.alloc() : memref<3x1024x1024xf32>

  // CHECK-DAG: %[[transformA:.*]] = rock.transform %{{.*}} by <affine_map<(d0, d1, d2, d3, d4, d5, d6, d7, d8) -> (d1, ((d0 * 2 + d6) * 2 + d4) * 8 + d8, (d2 + d7) * 128 + d5)> by [<PassThrough ["g_block"] at [1] -> ["g"] at [0]>, <Unmerge{24, 2, 2, 8} ["k_loop", "k_repeat", "k_thread", "k_iter"] at [0, 6, 4, 8] -> ["k"] at [1]>, <Unmerge{8, 1, 128} ["m_block", "m_iter", "m_thread"] at [2, 7, 5] -> ["m"] at [2]>, <AddDim{8} ["n_block"] at [3] -> [] at []>] bounds = [24, 3, 8, 8, 2, 128, 2, 1, 8] -> [3, 768, 1024]> : memref<3x768x1024xf16> to memref<24x3x8x8x2x128x2x1x8xf16>
  // CHECK-DAG: %[[transformA2:.*]] = rock.transform %[[transformA]] by <affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4 floordiv 128, d4 mod 128, d5 floordiv 8, 0, d5 mod 8)> by [<PassThrough ["k_loop", "g_block", "m_block", "n_block"] at [0, 1, 2, 3] -> ["k_loop", "g_block", "m_block", "n_block"] at [0, 1, 2, 3]>, <Merge{2, 128} ["tid"] at [4] -> ["k_thread", "m_thread"] at [4, 5]>, <Merge{2, 1, 8} ["iter"] at [5] -> ["k_repeat", "m_iter", "k_iter"] at [6, 7, 8]>] bounds = [24, 3, 8, 8, 256, 16] -> [24, 3, 8, 8, 2, 128, 2, 1, 8]> : memref<24x3x8x8x2x128x2x1x8xf16> to memref<24x3x8x8x256x16xf16>

  // CHECK: rock.threadwise_read_into {{.*}}(%[[transformA2]]) {{.*}} : memref<24x3x8x8x256x16xf16> -> memref<16xf16, #gpu.address_space<private>>, vector<16xi1>
  
  // CHECK-DAG: %[[transformB:.*]] = rock.transform %{{.*}} by <affine_map<(d0, d1, d2, d3, d4, d5, d6, d7, d8) -> (d1, ((d0 * 2 + d6) * 2 + d4) * 8 + d8, (d3 + d7) * 128 + d5)> by [<PassThrough ["g_block"] at [1] -> ["g"] at [0]>, <Unmerge{24, 2, 2, 8} ["k_loop", "k_repeat", "k_thread", "k_iter"] at [0, 6, 4, 8] -> ["k"] at [1]>, <Unmerge{8, 1, 128} ["n_block", "n_iter", "n_thread"] at [3, 7, 5] -> ["n"] at [2]>, <AddDim{8} ["m_block"] at [2] -> [] at []>] bounds = [24, 3, 8, 8, 2, 128, 2, 1, 8] -> [3, 768, 1024]> : memref<3x768x1024xf16> to memref<24x3x8x8x2x128x2x1x8xf16>
  // CHECK-DAG: %[[transformB2:.*]] = rock.transform %[[transformB]] by <affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4 floordiv 128, d4 mod 128, d5 floordiv 8, 0, d5 mod 8)> by [<PassThrough ["k_loop", "g_block", "m_block", "n_block"] at [0, 1, 2, 3] -> ["k_loop", "g_block", "m_block", "n_block"] at [0, 1, 2, 3]>, <Merge{2, 128} ["tid"] at [4] -> ["k_thread", "n_thread"] at [4, 5]>, <Merge{2, 1, 8} ["iter"] at [5] -> ["k_repeat", "n_iter", "k_iter"] at [6, 7, 8]>] bounds = [24, 3, 8, 8, 256, 16] -> [24, 3, 8, 8, 2, 128, 2, 1, 8]> : memref<24x3x8x8x2x128x2x1x8xf16> to memref<24x3x8x8x256x16xf16>
  
  // CHECK: rock.threadwise_read_into {{.*}}[](%[[transformB2]]) {{.*}} : memref<24x3x8x8x256x16xf16> -> memref<16xf16, #gpu.address_space<private>>, vector<16xi1>

  // CHECK-DAG: %[[transformLDSA:.*]] = rock.transform %{{.*}} by <affine_map<(d0, d1, d2, d3, d4) -> ((d2 * 2 + d0) * 8 + d4, d3 * 128 + d1)> by [<Unmerge{2, 2, 8} ["kouterPerThread", "k_thread", "kpackPerThread"] at [2, 0, 4] -> ["k"] at [0]>, <Unmerge{1, 128} ["m_iter", "m_thread"] at [3, 1] -> ["m"] at [1]>] bounds = [2, 128, 2, 1, 8] -> [32, 128]> : memref<32x128xvector<8xf16>, #gpu.address_space<workgroup>> to memref<2x128x2x1x8xvector<8xf16>, #gpu.address_space<workgroup>>
  // CHECK-DAG: %[[transformLDSA2:.*]] = rock.transform %[[transformLDSA]] by <affine_map<(d0, d1) -> (d0 floordiv 128, d0 mod 128, d1 floordiv 8, 0, d1 mod 8)> by [<Merge{2, 128} ["tid"] at [0] -> ["k_thread", "m_thread"] at [0, 1]>, <Merge{2, 1, 8} ["iter"] at [1] -> ["kouterPerThread", "m_iter", "kpackPerThread"] at [2, 3, 4]>] bounds = [256, 16] -> [2, 128, 2, 1, 8]> : memref<2x128x2x1x8xvector<8xf16>, #gpu.address_space<workgroup>> to memref<256x16xvector<8xf16>, #gpu.address_space<workgroup>>
  
  // CHECK: rock.threadwise_write_all {{.*}}(%[[transformLDSA2]]) {{.*}} memref<16xf16, #gpu.address_space<private>> -> memref<256x16xvector<8xf16>, #gpu.address_space<workgroup>>

  // CHECK-DAG: %[[transformLDSB:.*]] = rock.transform %{{.*}} by <affine_map<(d0, d1, d2, d3, d4) -> ((d2 * 2 + d0) * 8 + d4, d3 * 128 + d1)> by [<Unmerge{2, 2, 8} ["kouterPerThread", "k_thread", "kpackPerThread"] at [2, 0, 4] -> ["k"] at [0]>, <Unmerge{1, 128} ["n_iter", "n_thread"] at [3, 1] -> ["n"] at [1]>] bounds = [2, 128, 2, 1, 8] -> [32, 128]> : memref<32x128xvector<8xf16>, #gpu.address_space<workgroup>> to memref<2x128x2x1x8xvector<8xf16>, #gpu.address_space<workgroup>>
  // CHECK-DAG: %[[transformLDSB2:.*]] = rock.transform %[[transformLDSB]] by <affine_map<(d0, d1) -> (d0 floordiv 128, d0 mod 128, d1 floordiv 8, 0, d1 mod 8)> by [<Merge{2, 128} ["tid"] at [0] -> ["k_thread", "n_thread"] at [0, 1]>, <Merge{2, 1, 8} ["iter"] at [1] -> ["kouterPerThread", "n_iter", "kpackPerThread"] at [2, 3, 4]>] bounds = [256, 16] -> [2, 128, 2, 1, 8]> : memref<2x128x2x1x8xvector<8xf16>, #gpu.address_space<workgroup>> to memref<256x16xvector<8xf16>, #gpu.address_space<workgroup>>

  // CHECK: rock.threadwise_write_all {{.*}}(%[[transformLDSB2]]) {{.*}} memref<16xf16, #gpu.address_space<private>> -> memref<256x16xvector<8xf16>, #gpu.address_space<workgroup>>

  rock.gridwise_gemm_accel(%7, %8, %alloc) storeMethod( set) features =  mfma|dot|atomic_add|atomic_add_f16|direct_to_lds_32b {aAccelLayout, arch = "amdgcn-amd-amdhsa:gfx942:sramecc+:xnack-", bAccelLayout, blockSize = 256 : i32, gridSize = 192 : i32, numCU = 228 : i32, params = #rock.xdlops_gemm_derived_params<kpackPerBlock = 4, mPerBlock = 128, nPerBlock = 128, kpack = 8, mPerWave = 32, nPerWave = 128, mnPerXdl = 32, splitKFactor = 1, scheduleVersion = 2, outputSwizzle = 2, forceUnroll = true>} : memref<3x768x1024xf16>, memref<3x768x1024xf16>, memref<3x1024x1024xf32>
  linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%alloc : memref<3x1024x1024xf32>) outs(%0 : memref<3x1024x1024xf16>) attrs =  {rock.majorTensorNumber = 0 : index} {
  ^bb0(%in: f32, %out: f16):
    %9 = arith.truncf %in : f32 to f16
    linalg.yield %9 : f16
  }
  return
}
