// RUN: rocmlir-opt --rock-sugar-to-loops %s | FileCheck %s

module {
// CHECK-LABEL: func.func @load_scalar_in_bounds
// CHECK-SAME: (%[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @load_scalar_in_bounds(%mem: memref<1x2x3x4x8xf32>) -> f32 {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = memref.load %[[cast]]
    %ret = rock.global_load %mem[%c0, %c0, %c0, %c0, %c0] if %true
        : memref<1x2x3x4x8xf32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}

// CHECK-LABEL: func.func @load_scalar_in_bounds_force_oob
// CHECK-SAME: (%[[mem:.*]]: memref<8xf32>)
func.func @load_scalar_in_bounds_force_oob(%mem: memref<8xf32>) -> f32 {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK: %[[ret:.*]] = amdgpu.raw_buffer_load %[[mem]]
    %ret = rock.global_load %mem[%c0] if %true
        {canReadOffEnd}
        : memref<8xf32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}


// CHECK-LABEL: func.func @load_vector_in_bounds
// CHECK-SAME: (%[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @load_vector_in_bounds(%mem: memref<1x2x3x4x8xf32>) -> vector<5xf32> {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = vector.load %[[cast]]
    %ret = rock.global_load %mem[%c0, %c0, %c0, %c0, %c0] if %true
        : memref<1x2x3x4x8xf32>  -> vector<5xf32>
    // CHECK: return %[[ret]]
    return %ret : vector<5xf32>
}

// CHECK-LABEL: func.func @load_vector_oob
// CHECK-SAME: (%[[mem:.*]]: memref<1x2x3x4x8xf32>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @load_vector_oob(%mem: memref<1x2x3x4x8xf32>, %idx: index, %valid: i1) -> vector<5xf32> {
    %c0 = arith.constant 0 : index
    // CHECK: %[[c192:.*]] = arith.constant 192
    // CHECK: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-COUNT-2: amdgpu.raw_buffer_load %[[mem]]
    %ret = rock.global_load %mem[%c0, %c0, %c0, %c0, %idx] if %valid
        : memref<1x2x3x4x8xf32> -> vector<5xf32>
    return %ret : vector<5xf32>
}

// CHECK-LABEL: func.func @load_scalar
// CHECK-SAME: (%[[mem:.*]]: memref<f32>)
func.func @load_scalar(%mem: memref<f32>) -> f32 {
    %true = arith.constant true
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = memref.load %[[cast]][] : memref<f32, #gpu.address_space<global>>
    %ret = rock.global_load %mem[] if %true
        : memref<f32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}

// Ensure that offsets that can be in [2 GB, 4 GB) go to buffer loads.
// CHECK-LABEL: func.func @load_scalar_in_bounds_semi_large
// CHECK-SAME: (%[[mem:.*]]: memref<32769x16384xf32>)
func.func @load_scalar_in_bounds_semi_large(%mem: memref<32769x16384xf32>) -> f32 {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK: %[[ret:.*]] = amdgpu.raw_buffer_load {boundsCheck = false} %[[mem]]
    %ret = rock.global_load %mem[%c0, %c0] if %true
        : memref<32769x16384xf32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}

// CHECK-LABEL: func.func @load_scalar_in_bounds_large
// CHECK-SAME: (%[[mem:.*]]: memref<1073741825xf32>)
func.func @load_scalar_in_bounds_large(%mem: memref<1073741825xf32>) -> f32 {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = memref.load %[[cast]]
    %ret = rock.global_load %mem[%c0] if %true {needs64BitIdx}
        : memref<1073741825xf32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}

// CHECK-LABEL: func.func @load_scalar_oob_large
// CHECK-SAME: (%[[mem:.*]]: memref<1073741825xf32>, %[[valid:.*]]: i1)
func.func @load_scalar_oob_large(%mem: memref<1073741825xf32>, %valid: i1) -> f32 {
    %c0 = arith.constant 0 : index
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = scf.if %[[valid]]
    // CHECK: %[[load:.*]] = memref.load %[[cast]]
    // CHECK: scf.yield %[[load]]
    %ret = rock.global_load %mem[%c0] if %valid {needs64BitIdx}
        : memref<1073741825xf32> -> f32
    // CHECK: return %[[ret]]
    return %ret : f32
}

// CHECK-LABEL: func.func @load_scalar_oob_large_i4
// CHECK-SAME: (%[[mem:.*]]: memref<1073741825xi4>, %[[valid:.*]]: i1)
func.func @load_scalar_oob_large_i4(%mem: memref<1073741825xi4>, %valid: i1) -> i4 {
    %c0 = arith.constant 0 : index
    // CHECK: %[[zero:.*]] = arith.constant 0 : i4
    // CHECK: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: %[[ret:.*]] = scf.if %[[valid]] -> (i4)
    // CHECK: %[[load:.*]] = vector.load %[[cast]]
    // CHECK-SAME: memref<1073741825xi4, #gpu.address_space<global>>, vector<2xi4>
    // CHECK: %[[element:.*]] = vector.extract %[[load]]
    // CHECK: scf.yield %[[element]]
    // CHECK: } else {
    // CHECK: scf.yield %[[zero]] : i4
    %ret = rock.global_load %mem[%c0] if %valid {needs64BitIdx}
        : memref<1073741825xi4> -> i4
    // CHECK: return %[[ret]]
    return %ret : i4
}

// CHECK-LABEL: func.func @store_scalar_in_bounds
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @store_scalar_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.store %[[val]], %[[cast]]
    rock.global_store set %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
        {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @store_vector_in_bounds
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @store_vector_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = vector.transfer_read %[[source]]
    // CHECK: vector.store %[[val]], %[[cast]]
    rock.global_store set %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
        {length = 5 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @store_vector_oob
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @store_vector_oob(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>, %idx: index, %valid: i1) {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-COUNT-2: amdgpu.raw_buffer_store %{{.*}} -> %[[mem]]
    // CHECK-NEXT: return
    rock.global_store set %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
        {length = 5 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @store_scalar_in_scalar
// CHECK-SAME: (%[[source:.*]]: memref<1xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<f32>)
func.func @store_scalar_in_scalar(%source: memref<1xf32, #gpu.address_space<private>>, %mem: memref<f32>) {
    %true = arith.constant true
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.store %[[val]], %[[cast]]
    rock.global_store set %source[%c0] -> %mem[] if %true
        {length = 1 : index}
        : memref<1xf32, #gpu.address_space<private>> -> memref<f32>
    return
}

// Some nightly tests failed if this wasn't a buffer store
// CHECK-LABEL: func.func @store_in_scalar_maybe_oob
// CHECK-SAME: (%[[source:.*]]: memref<1xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<f32>, %[[valid:.*]]: i1)
func.func @store_in_scalar_maybe_oob(%source: memref<1xf32, #gpu.address_space<private>>, %mem: memref<f32>, %valid: i1) {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK-DAG: %[[exp:.*]] = memref.expand_shape %[[mem]] []
    // CHECK: amdgpu.raw_buffer_store %[[val]] -> %[[exp]]
    rock.global_store set %source[%c0] -> %mem[] if %valid
        {length = 1 : index}
        : memref<1xf32, #gpu.address_space<private>> -> memref<f32>
    return
}

// CHECK-LABEL: func.func @store_scalar_in_bounds_semi_large
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<32769x16384xf32>)
func.func @store_scalar_in_bounds_semi_large(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<32769x16384xf32>) {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: amdgpu.raw_buffer_store {boundsCheck = false} %[[val]] -> %[[mem]]
    rock.global_store set %source[%c0] -> %mem[%c0, %c0] if %true
        {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<32769x16384xf32>
    return
}

// CHECK-LABEL: func.func @store_scalar_in_bounds_large
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1073741825xf32>)
func.func @store_scalar_in_bounds_large(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1073741825xf32>) {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.store %[[val]], %[[cast]]
    rock.global_store set %source[%c0] -> %mem[%c0] if %true
         {length = 1 : index, needs64BitIdx}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1073741825xf32>
    return
}

// CHECK-LABEL: func.func @store_scalar_oob_large
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1073741825xf32>, %[[valid:.*]]: i1)
func.func @store_scalar_oob_large(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1073741825xf32>, %valid: i1) {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK: scf.if %[[valid]]
    // CHECK: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.store %[[val]], %[[cast]]
    rock.global_store set %source[%c0] -> %mem[%c0] if %valid
         {length = 1 : index, needs64BitIdx}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1073741825xf32>
    return
}

// CHECK-LABEL: func.func @add_scalar_in_bounds
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @add_scalar_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) attributes {features = #rock<GemmFeatures atomic_add>} {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.atomic_rmw addf %[[val]], %[[cast]]
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
         {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @add_scalar_oob
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_oob(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK-DAG: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[mem]]
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @add_scalar_oob_fp16
// CHECK-SAME: (%[[source:.*]]: memref<5xf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_oob_fp16(%source: memref<5xf16, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_f16>} {
    %c0 = arith.constant 0 : index
    // CHECK: %[[mod:.*]] = arith.remui
    // CHECK: %[[cmp:.*]] = arith.cmpi ne, %[[mod]]
    // CHECK: %[[val:.*]] = arith.select %[[cmp]], {{.*}} : vector<2xf16>
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[mem]][{{.*}}] : vector<2xf16>
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 1 : index}
        : memref<5xf16, #gpu.address_space<private>> -> memref<1x2x3x4x8xf16>
    return
}

// CHECK-LABEL: func.func @add_scalar_oob_bf16
// CHECK-SAME: (%[[source:.*]]: memref<5xbf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xbf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_oob_bf16(%source: memref<5xbf16, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xbf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_bf16>} {
    %c0 = arith.constant 0 : index
    // CHECK: %[[mod:.*]] = arith.remui
    // CHECK: %[[cmp:.*]] = arith.cmpi ne, %[[mod]]
    // CHECK: %[[val:.*]] = arith.select %[[cmp]], {{.*}} : vector<2xbf16>
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[mem]][{{.*}}] : vector<2xbf16>
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 1 : index}
        : memref<5xbf16, #gpu.address_space<private>> -> memref<1x2x3x4x8xbf16>
    return
}

// CHECK-LABEL:  func.func @add_scalar_last_dim_odd_fp16
// CHECK-SAME  (%[[source:.*]]: memref<5xf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x16x15xf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_last_dim_odd_fp16(%source: memref<5xf16, #gpu.address_space<private>>, %mem: memref<1x16x15xf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_f16>} {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    // CHECK: %[[c16:.*]] = arith.constant 16 : i32
    // CHECK: %[[c2:.*]] = arith.constant 2 : i32
    // CHECK: %[[c1:.*]] = arith.constant 1 : i32
    // CHECK: %[[c0:.*]] = arith.constant 0 : i32
    // CHECK: %[[c15:.*]] = arith.constant 15 : i32
    // CHECK: %[[i:.*]] = arith.index_cast {{.*}} : index to i32
    // CHECK: %[[j:.*]] = arith.index_cast {{.*}} : index to i32
    // CHECK: %[[partial:.*]] = arith.muli %[[i]], %[[c15]] : i32
    // CHECK: %[[flat:.*]] = arith.addi %[[j]], %[[partial]] : i32
    // CHECK: %[[rem:.*]] = arith.remui %[[flat]], %[[c2]]
    // CHECK: %[[cmp:.*]] = arith.cmpi ne, %[[rem]], %[[c0]]
    // CHECK: %[[addr:.*]] = arith.select %[[cmp]], {{.*}}, {{.*}} : i32
    // CHECK: %[[unflat1:.*]] = arith.remui %[[addr]], %[[c15]] : i32
    // CHECK: %[[unflat0_0:.*]] = arith.divui %[[addr]], %[[c15]] : i32
    // CHECK: %[[unflat0:.*]] = arith.remui %[[unflat0_0]], %[[c16]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd {{.*}} -> {{.*}}[%[[c0]], %[[unflat0]], %[[unflat1]]]
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c1, %idx] if %valid
         {length = 1 : index}
        : memref<5xf16, #gpu.address_space<private>> -> memref<1x16x15xf16>
    return
}

// CHECK-LABEL:  func.func @add_scalar_last_dim_odd_bf16
// CHECK-SAME  (%[[source:.*]]: memref<5xbf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x16x15xbf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_last_dim_odd_bf16(%source: memref<5xbf16, #gpu.address_space<private>>, %mem: memref<1x16x15xbf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_bf16>} {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    // CHECK: %[[c16:.*]] = arith.constant 16 : i32
    // CHECK: %[[c2:.*]] = arith.constant 2 : i32
    // CHECK: %[[c1:.*]] = arith.constant 1 : i32
    // CHECK: %[[c0:.*]] = arith.constant 0 : i32
    // CHECK: %[[c15:.*]] = arith.constant 15 : i32
    // CHECK: %[[i:.*]] = arith.index_cast {{.*}} : index to i32
    // CHECK: %[[j:.*]] = arith.index_cast {{.*}} : index to i32
    // CHECK: %[[partial:.*]] = arith.muli %[[i]], %[[c15]] : i32
    // CHECK: %[[flat:.*]] = arith.addi %[[j]], %[[partial]] : i32
    // CHECK: %[[rem:.*]] = arith.remui %[[flat]], %[[c2]]
    // CHECK: %[[cmp:.*]] = arith.cmpi ne, %[[rem]], %[[c0]]
    // CHECK: %[[addr:.*]] = arith.select %[[cmp]], {{.*}}, {{.*}} : i32
    // CHECK: %[[unflat1:.*]] = arith.remui %[[addr]], %[[c15]] : i32
    // CHECK: %[[unflat0_0:.*]] = arith.divui %[[addr]], %[[c15]] : i32
    // CHECK: %[[unflat0:.*]] = arith.remui %[[unflat0_0]], %[[c16]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd {{.*}} -> {{.*}}[%[[c0]], %[[unflat0]], %[[unflat1]]]
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c1, %idx] if %valid
         {length = 1 : index}
        : memref<5xbf16, #gpu.address_space<private>> -> memref<1x16x15xbf16>
    return
}

// CHECK-LABEL:  func.func @add_scalar_all_dims_odd_fp16
// CHECK-SAME:  (%[[source:.*]]: memref<5xf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x15x15xf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_all_dims_odd_fp16(%source: memref<5xf16, #gpu.address_space<private>>, %mem: memref<1x15x15xf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_f16>} {
    // CHECK: %[[c224:.*]] = arith.constant 224 : i32
    // CHECK: %[[notlastelem:.*]] = arith.cmpi ult, {{.*}}, %[[c224]] : i32
    // CHECK: scf.if %[[notlastelem]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd
    // CHECK: else
    // CHECK: memref.atomic_rmw addf
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c1, %idx] if %valid
         {length = 1 : index}
        : memref<5xf16, #gpu.address_space<private>> -> memref<1x15x15xf16>
    return
}

// CHECK-LABEL:  func.func @add_scalar_all_dims_odd_bf16
// CHECK-SAME:  (%[[source:.*]]: memref<5xbf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x15x15xbf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_scalar_all_dims_odd_bf16(%source: memref<5xbf16, #gpu.address_space<private>>, %mem: memref<1x15x15xbf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_bf16>} {
    // CHECK: %[[c224:.*]] = arith.constant 224 : i32
    // CHECK: %[[notlastelem:.*]] = arith.cmpi ult, {{.*}}, %[[c224]] : i32
    // CHECK: scf.if %[[notlastelem]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd
    // CHECK: else
    // CHECK: memref.atomic_rmw addf
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c1, %idx] if %valid
         {length = 1 : index}
        : memref<5xbf16, #gpu.address_space<private>> -> memref<1x15x15xbf16>
    return
}

// CHECK-LABEL: func.func @add_packed_oob_fp16
// CHECK-SAME: (%[[source:.*]]: memref<5xf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_packed_oob_fp16(%source: memref<5xf16, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_f16>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK-DAG: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-DAG: %[[val:.*]] = vector.transfer_read %[[source]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[mem]][{{.*}}] : vector<2xf16>
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 2 : index}
        : memref<5xf16, #gpu.address_space<private>> -> memref<1x2x3x4x8xf16>
    return
}

// CHECK-LABEL: func.func @add_packed_oob_bf16
// CHECK-SAME: (%[[source:.*]]: memref<5xbf16, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xbf16>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @add_packed_oob_bf16(%source: memref<5xbf16, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xbf16>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add_bf16>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK-DAG: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-DAG: %[[val:.*]] = vector.transfer_read %[[source]]
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[mem]][{{.*}}] : vector<2xbf16>
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 2 : index}
        : memref<5xbf16, #gpu.address_space<private>> -> memref<1x2x3x4x8xbf16>
    return
}

// CHECK-LABEL: func.func @add_vector_in_bounds
func.func @add_vector_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) attributes {features = #rock<GemmFeatures atomic_add>} {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-5: amdgpu.raw_buffer_atomic_fadd
    rock.global_store atomic_add %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
         {length = 5 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @add_scalar_to_scalar_valid
// CHECK-SAME: (%[[source:.*]]: memref<1xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<f32>)
func.func @add_scalar_to_scalar_valid(%source: memref<1xf32, #gpu.address_space<private>>, %mem: memref<f32>) attributes {features = #rock<GemmFeatures atomic_add>} {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK-NOT: scf.if
    // CHECK: memref.atomic_rmw addf %[[val]], %[[cast]]
    rock.global_store atomic_add %source[%c0] -> %mem[] if %true
         {length = 1 : index}
        : memref<1xf32, #gpu.address_space<private>> -> memref<f32>
    return
}

// CHECK-LABEL: func.func @add_scalar_to_scalar_maybe_valid
// CHECK-SAME: (%[[source:.*]]: memref<1xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<f32>, %[[valid:.*]]: i1)
func.func @add_scalar_to_scalar_maybe_valid(%source: memref<1xf32, #gpu.address_space<private>>, %mem: memref<f32>, %valid: i1) attributes {features = #rock<GemmFeatures atomic_add>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK-DAG: %[[exp:.*]] = memref.expand_shape %[[mem]] []
    // CHECK: amdgpu.raw_buffer_atomic_fadd %[[val]] -> %[[exp]]
    rock.global_store atomic_add %source[%c0] -> %mem[] if %valid
         {length = 1 : index}
        : memref<1xf32, #gpu.address_space<private>> -> memref<f32>
    return
}

// CHECK-LABEL: func.func @native_fmax_scalar_in_bounds
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @native_fmax_scalar_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) attributes {features = #rock<GemmFeatures atomic_fmax_f32>} {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.atomic_rmw maximumf %[[val]], %[[cast]]
    rock.global_store atomic_max %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
          {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @native_fmax_scalar_oob
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @native_fmax_scalar_oob(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_fmax_f32>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK-DAG: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: amdgpu.raw_buffer_atomic_fmax %[[val]] -> %[[mem]]
    rock.global_store atomic_max %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @emulated_fmax_scalar_in_bounds
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>)
func.func @emulated_fmax_scalar_in_bounds(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>) {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // CHECK-DAG: %[[cast:.*]] = memref.memory_space_cast %[[mem]]
    // CHECK-SAME: #gpu.address_space<global>
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: memref.atomic_rmw maximumf %[[val]], %[[cast]]
    rock.global_store atomic_max %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %c0] if %true
         {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @emulated_fmax_scalar_oob
// CHECK-SAME: (%[[source:.*]]: memref<5xf32, #gpu.address_space<private>>, %[[mem:.*]]: memref<1x2x3x4x8xf32>, %[[idx:.*]]: index, %[[valid:.*]]: i1)
func.func @emulated_fmax_scalar_oob(%source: memref<5xf32, #gpu.address_space<private>>, %mem: memref<1x2x3x4x8xf32>, %idx: index, %valid: i1) attributes {features = #rock<GemmFeatures atomic_fmax_f32>} {
    %c0 = arith.constant 0 : index
    // CHECK-DAG: %[[c192:.*]] = arith.constant 192
    // CHECK-DAG: arith.select %[[valid]], %[[idx]], %[[c192]]
    // CHECK-DAG: %[[val:.*]] = memref.load %[[source]]
    // CHECK: amdgpu.raw_buffer_atomic_fmax %[[val]] -> %[[mem]]
    rock.global_store atomic_max %source[%c0] -> %mem[%c0, %c0, %c0, %c0, %idx] if %valid
         {length = 1 : index}
        : memref<5xf32, #gpu.address_space<private>> -> memref<1x2x3x4x8xf32>
    return
}

// CHECK-LABEL: func.func @load_4bit_boundary_case
// CHECK-SAME: (%[[mem:.*]]: memref<4294967295xi4>)
func.func @load_4bit_boundary_case(%mem: memref<4294967295xi4>) -> i4 {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // 4294967295 elements * 4 bits = 17179869180 bits
    // ceil(17179869180 / 8) = 2147483648 bytes = exactly 2^31 bytes
    // This triggers numBytes.trunc(32).isNegative() without needs64BitIdx
    // CHECK: %[[c0_i32:.*]] = arith.constant 0 : i32
    // CHECK: %[[vec:.*]] = amdgpu.raw_buffer_load {boundsCheck = false} %[[mem]][%[[c0_i32]]]
    // CHECK-SAME: memref<4294967295xi4>, i32 -> vector<2xi4>
    // CHECK: %[[elem:.*]] = vector.extract %[[vec]][0]
    // CHECK: return %[[elem]] : i4
    %ret = rock.global_load %mem[%c0] if %true
        : memref<4294967295xi4> -> i4
    return %ret : i4
}

// CHECK-LABEL: func.func @load_4bit_vector_boundary_case
// CHECK-SAME: (%[[mem:.*]]: memref<4294967295xi4>)
func.func @load_4bit_vector_boundary_case(%mem: memref<4294967295xi4>) -> vector<3xi4> {
    %c0 = arith.constant 0 : index
    %true = arith.constant true
    // Same as above but loading a vector
    // CHECK: %[[c2_i32:.*]] = arith.constant 2 : i32
    // CHECK: %[[c0_i32:.*]] = arith.constant 0 : i32
    // CHECK: amdgpu.raw_buffer_load {boundsCheck = false} %[[mem]][%[[c0_i32]]]
    // CHECK-SAME: memref<4294967295xi4>, i32 -> vector<2xi4>
    // CHECK: amdgpu.raw_buffer_load {boundsCheck = false} %[[mem]][%[[c2_i32]]]
    // CHECK-SAME: memref<4294967295xi4>, i32 -> i4
    %ret = rock.global_load %mem[%c0] if %true
        : memref<4294967295xi4> -> vector<3xi4>
    return %ret : vector<3xi4>
}

// CHECK-LABEL: func.func @load_paged_scalar
// CHECK-SAME: (%[[mem:.*]]: memref<1x64x8192xf16>, %[[pagePtr:.*]]: i64, %[[offset:.*]]: index)
func.func @load_paged_scalar(%mem: memref<1x64x8192xf16>, %pagePtr: i64, %offset: index) -> f16 attributes {arch = "amdgcn-amd-amdhsa:gfx942"} {
    %true = arith.constant true
    // Paged load converts page ptr to llvm.ptr, creates buffer resource, and loads
    // CHECK-DAG: %[[pageSizeBytes:.*]] = llvm.mlir.constant(16384 : i64) : i64
    // CHECK: %[[ptr:.*]] = llvm.inttoptr %[[pagePtr]] : i64 to !llvm.ptr<1>
    // CHECK: %[[rsrc:.*]] = rocdl.make.buffer.rsrc %[[ptr]], %{{.*}}, %[[pageSizeBytes]], %{{.*}} : <1> to <8>
    // CHECK: rocdl.raw.ptr.buffer.load %[[rsrc]]
    %ret = rock.global_load %mem[%offset] if %true paged %pagePtr {pageSize = 8192 : i64}
        : memref<1x64x8192xf16> -> f16
    return %ret : f16
}

// CHECK-LABEL: func.func @load_paged_vector
// CHECK-SAME: (%[[mem:.*]]: memref<1x64x8192xf16>, %[[pagePtr:.*]]: i64, %[[offset:.*]]: index)
func.func @load_paged_vector(%mem: memref<1x64x8192xf16>, %pagePtr: i64, %offset: index) -> vector<2xf16> attributes {arch = "amdgcn-amd-amdhsa:gfx942"} {
    %true = arith.constant true
    // Paged vector load converts page ptr to llvm.ptr, creates buffer resource, and loads
    // CHECK-DAG: %[[pageSizeBytes:.*]] = llvm.mlir.constant(16384 : i64) : i64
    // CHECK: %[[ptr:.*]] = llvm.inttoptr %[[pagePtr]] : i64 to !llvm.ptr<1>
    // CHECK: %[[rsrc:.*]] = rocdl.make.buffer.rsrc %[[ptr]], %{{.*}}, %[[pageSizeBytes]], %{{.*}} : <1> to <8>
    // CHECK: rocdl.raw.ptr.buffer.load %[[rsrc]]
    %ret = rock.global_load %mem[%offset] if %true paged %pagePtr {pageSize = 8192 : i64}
        : memref<1x64x8192xf16> -> vector<2xf16>
    return %ret : vector<2xf16>
}

// CHECK-LABEL: func.func @load_paged_vector_maybe_oob
// CHECK-SAME: (%[[mem:.*]]: memref<1x64x8192xf16>, %[[pagePtr:.*]]: i64, %[[offset:.*]]: index, %[[valid:.*]]: i1)
func.func @load_paged_vector_maybe_oob(%mem: memref<1x64x8192xf16>, %pagePtr: i64, %offset: index, %valid: i1) -> vector<2xf16> attributes {arch = "amdgcn-amd-amdhsa:gfx942"} {
    // Paged load with validity check - scf.if guards the buffer load
    // CHECK-DAG: %[[pageSizeBytes:.*]] = llvm.mlir.constant(16384 : i64) : i64
    // CHECK: %[[ptr:.*]] = llvm.inttoptr %[[pagePtr]] : i64 to !llvm.ptr<1>
    // CHECK: %[[rsrc:.*]] = rocdl.make.buffer.rsrc %[[ptr]], %{{.*}}, %[[pageSizeBytes]], %{{.*}} : <1> to <8>
    // CHECK: scf.if %[[valid]]
    // CHECK:   rocdl.raw.ptr.buffer.load %[[rsrc]]
    %ret = rock.global_load %mem[%offset] if %valid paged %pagePtr {pageSize = 8192 : i64}
        : memref<1x64x8192xf16> -> vector<2xf16>
    return %ret : vector<2xf16>
}

// CHECK-LABEL: func.func @load_paged_vector_large_page
// CHECK-SAME: (%[[mem:.*]]: memref<1x64x16384xf32>, %[[pagePtr:.*]]: i64, %[[offset:.*]]: index)
func.func @load_paged_vector_large_page(%mem: memref<1x64x16384xf32>, %pagePtr: i64, %offset: index) -> vector<4xf32> attributes {arch = "amdgcn-amd-amdhsa:gfx942"} {
    %true = arith.constant true
    // Larger page size (16384 elements * 4 bytes = 65536 bytes)
    // CHECK-DAG: %[[pageSizeBytes:.*]] = llvm.mlir.constant(65536 : i64) : i64
    // CHECK: %[[ptr:.*]] = llvm.inttoptr %[[pagePtr]] : i64 to !llvm.ptr<1>
    // CHECK: %[[rsrc:.*]] = rocdl.make.buffer.rsrc %[[ptr]], %{{.*}}, %[[pageSizeBytes]], %{{.*}} : <1> to <8>
    // CHECK: rocdl.raw.ptr.buffer.load %[[rsrc]]
    %ret = rock.global_load %mem[%offset] if %true paged %pagePtr {pageSize = 16384 : i64}
        : memref<1x64x16384xf32> -> vector<4xf32>
    return %ret : vector<4xf32>
}
}
