// RUN: rocmlir-opt -split-input-file -rock-gridwise-gemm-to-blockwise -canonicalize -verify-diagnostics %s | FileCheck %s

#xdlops_gemm_params1 = #rock.accel_gemm_params<kpackPerBlock = 8, mPerBlock = 128, nPerBlock = 128, kpack = 8, mPerWave = 64, nPerWave = 64, mnPerXdl = 32, splitKFactor = 1, scheduleVersion = 1, outputSwizzle = 2, wavesPerEU = 0, gridGroupSize = 0, forceUnroll = true>
#xdlops_gemm_params2 = #rock.accel_gemm_params<kpackPerBlock = 8, mPerBlock = 128, nPerBlock = 128, kpack = 8, mPerWave = 64, nPerWave = 64, mnPerXdl = 32, splitKFactor = 1, scheduleVersion = 2, outputSwizzle = 2, wavesPerEU = 0, gridGroupSize = 0, forceUnroll = true>

// CHECK-LABEL: @fp8_bf8_xdlops
func.func @fp8_bf8_xdlops(%arg0: memref<1x128x128xf8E4M3FNUZ>, %arg1: memref<1x128x115200xf8E5M2FNUZ>, %arg2: memref<1x128x115200xf32>) attributes {block_size = 256 : i32, grid_size = 900 : i32, rock.arch = "amdgcn-amd-amdhsa:gfx942", numCU = 228 : i32} {
  // The tuning testcase leads to padded buffers, we simplify here.
  // CHECK: %[[ldsA:.+]] = rock.alloc() : memref<8192xi8, #gpu.address_space<workgroup>>
  // CHECK: %[[ldsB:.+]] = rock.alloc() : memref<8192xi8, #gpu.address_space<workgroup>>

  // CHECK-DAG: %[[viewAGemm:.+]] = memref.view %[[ldsA]][{{.*}}][] : memref<8192xi8, #gpu.address_space<workgroup>> to memref<1024xvector<8xf8E4M3FNUZ>, #gpu.address_space<workgroup>>
  // CHECK-DAG: %[[viewBGemm:.+]] = memref.view %[[ldsB]][{{.*}}][] : memref<8192xi8, #gpu.address_space<workgroup>> to memref<1024xvector<8xf8E5M2FNUZ>, #gpu.address_space<workgroup>>

  // CHECK: scf.for
  // CHECK: rock.blockwise_load_tile %arg1{{.*}} LDS -> %[[ldsB]] -> %[[regB:[0-9]+]]
  // CHECK-SAME: loadType = #rock<GemmLoadTileType Default>
  // CHECK: rock.blockwise_load_tile %arg0{{.*}} LDS -> %[[ldsA]] -> %[[regA:[0-9]+]]
  // CHECK-SAME: loadType = #rock<GemmLoadTileType Default>
  // CHECK: rock.stage
  // CHECK: rock.blockwise_gemm_accel %{{.*}} += %[[regA]] from %[[viewAGemm]] * %[[regB]] from %[[viewBGemm]]
  // CHECK: rock.yield
  // CHECK: {name = "MMA"}
  // CHECK: {rock.pipeline = #rock.rock.pipeline<2>}
  rock.gridwise_gemm_accel(%arg0, %arg1, %arg2) storeMethod( set) {blockSize = 256 : i32, gridSize = 900 : i32, params = #xdlops_gemm_params1} : memref<1x128x128xf8E4M3FNUZ>, memref<1x128x115200xf8E5M2FNUZ>, memref<1x128x115200xf32>
  return
}

// CHECK-LABEL: @fp8_bf8_xdlops_schedulev2
func.func @fp8_bf8_xdlops_schedulev2(%arg0: memref<1x128x128xf8E4M3FNUZ>, %arg1: memref<1x128x115200xf8E5M2FNUZ>, %arg2: memref<1x128x115200xf32>) attributes {block_size = 256 : i32, grid_size = 900 : i32, rock.arch = "amdgcn-amd-amdhsa:gfx942", numCU = 228 : i32} {
  // The tuning testcase leads to padded buffers, we simplify here.
  // CHECK: %[[ldsA:.+]] = rock.alloc() : memref<8192xi8, #gpu.address_space<workgroup>>
  // CHECK: %[[ldsB:.+]] = rock.alloc() : memref<8192xi8, #gpu.address_space<workgroup>>

  // CHECK: scf.for
  // CHECK: rock.blockwise_load_tile %arg1{{.*}} LDS -> %[[ldsB]] -> %[[regB:[0-9]+]]
  // CHECK-SAME: loadType = #rock<GemmLoadTileType DoubleBuffer>
  // CHECK: rock.blockwise_load_tile %arg0{{.*}} LDS -> %[[ldsA]] -> %[[regA:[0-9]+]]
  // CHECK-SAME: loadType = #rock<GemmLoadTileType DoubleBuffer>
  // CHECK: rock.stage
  // CHECK: rock.blockwise_gemm_accel %{{.*}} += %[[regA]] * %[[regB]]
  // CHECK-NOT: from
  // CHECK: rock.yield
  // CHECK: {name = "MMA"}
  // CHECK: {rock.pipeline = #rock.rock.pipeline<1>}
  rock.gridwise_gemm_accel(%arg0, %arg1, %arg2) storeMethod( set) {blockSize = 256 : i32, gridSize = 900 : i32, params = #xdlops_gemm_params2} : memref<1x128x128xf8E4M3FNUZ>, memref<1x128x115200xf8E5M2FNUZ>, memref<1x128x115200xf32>
  return
}
