//===- QuickTuningClassifier.h - ML-based tuning config filter ------------===//
//
// Part of the MLIR Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lightweight decision-tree ensemble classifier for filtering tuning
// configurations. Trees are generated by trainClassifier.py and stored as
// flat constexpr arrays in QuickTuningClassifier.inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H
#define MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H

#include "mlir/Dialect/Rock/IR/Rock.h"
#include "mlir/Dialect/Rock/Tuning/GridwiseGemmParams.h"

namespace mlir {
namespace rock {

/// Returns true if the classifier accepts this (problem, config) pair, or if
/// no classifier is available for the given (op, arch, dtype) combination.
bool classifierAcceptsConfig(const PopulateParamsInfo &info,
                             AccelGemmParamsAttr params);

} // namespace rock
} // namespace mlir

#endif // MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H
