//===- QuickTuningClassifier.h - ML-based tuning config filter ------------===//
//
// Part of the MLIR Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lightweight decision-tree ensemble classifier for filtering tuning
// configurations. Trees are generated by trainClassifier.py and stored as
// flat constexpr arrays in QuickTuningClassifier.inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H
#define MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H

#include "mlir/Dialect/Rock/IR/GemmGemmSize.h"
#include "mlir/Dialect/Rock/IR/Rock.h"
#include "mlir/Dialect/Rock/Tuning/GridwiseGemmParams.h"

#include <optional>

namespace mlir {
namespace rock {

/// Return the raw classifier score for a (problem, config) pair.
/// Higher score = more likely to be performant.
/// Returns std::nullopt if no classifier is available for the given
/// (op, arch, dtype) combination.
std::optional<float> classifierScoreConfig(const PopulateParamsInfo &info,
                                           AccelGemmParamsAttr params);

/// Overload for attention (GemmGemm) parameters.
std::optional<float> classifierScoreConfig(KernelType kernelType,
                                           StringRef arch, Type dataType,
                                           const GemmGemmSize &gemmSize,
                                           uint32_t numCu,
                                           GemmGemmParamsAttr params);

} // namespace rock
} // namespace mlir

#endif // MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGCLASSIFIER_H
