// RUN: mlir-miopen-lib-test --args " --x2 1 --operation conv2d --arch amdgcn-amd-amdhsa:gfx900 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv2d_nchw_kcyx_nkhw --groupsize 1" --option tuningparams; test $? -eq 0 || echo "expected failure" | FileCheck %s --check-prefix=GFX900_NO_XDLOPS
// RUN: mlir-miopen-lib-test --args " --x2 1 --operation conv2d --arch amdgcn-amd-amdhsa:gfx90a --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv2d_nchw_kcyx_nkhw --groupsize 1" --option tuningparams; test $? -eq 0 || echo "expected failure" | FileCheck %s --check-prefix=GFX90A_NO_XDLOPS
// RUN: mlir-miopen-lib-test --args " --operation conv2d --arch amdgcn-amd-amdhsa:gfx90a --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv2d_nchw_kcyx_nkhw --groupsize 1" --option tuningparams; test $? -eq 0 || echo "expected failure" | FileCheck %s --check-prefix=GFX90A_NO_NONXDLOPS
// RUN: mlir-miopen-lib-test --args " --operation conv2d --arch amdgcn-amd-amdhsa:gfx1030 --num_cu 64 --in_type fp32 --fil_type fp32 --out_type fp32 --fil_layout GNCHW --in_layout NGCHW --out_layout NGCHW --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --kernel_name conv2d_nchw_kcyx_nkhw --groupsize 1" --option tuningparams; test $? -eq 0 || echo "expected failure" | FileCheck %s --check-prefix=GFX1030_NO_NONXDLOPS

// GFX900_NO_XDLOPS: expected failure
// GFX90A_NO_XDLOPS: expected failure
// GFX90A_NO_NONXDLOPS: expected failure
// GFX1030_NO_NONXDLOPS: expected failure
