// RUN: mlir-opt --show-dialects | FileCheck %s
// CHECK: Available Dialects:
// CHECK: acc
// CHECK: affine
// CHECK: arm_neon
// CHECK: arm_sve
// CHECK: async
// CHECK: avx512
// CHECK: complex
// CHECK: gpu
// CHECK: linalg
// CHECK: llvm
// CHECK: llvm_arm_neon
// CHECK: llvm_arm_sve
// CHECK: llvm_avx512
// CHECK: nvvm
// CHECK: omp
// CHECK: pdl
// CHECK: pdl_interp
// CHECK: quant
// CHECK: rocdl
// CHECK: scf
// CHECK: sdbm
// CHECK: shape
// CHECK: spv
// CHECK: std
// CHECK: tensor
// CHECK: test
// CHECK: tosa
// CHECK: vector
