// Generated by copilot with the prompt "please generate a completely comprehensive test case for MIGraphXDialect::materializeConstant in lit"

// RUN: mlir-opt %s -split-input-file | FileCheck %s

//===----------------------------------------------------------------------===//
// Valid: float splat
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @float_splat
  func.func @float_splat() -> !migraphx.shaped<2x3xf32, 6x2x1> {
    %c = "migraphx.literal"() {value = dense<1.5> : tensor<2x3xf32>} : () -> !migraphx.shaped<2x3xf32, 6x2x1>
    // CHECK: migraphx.literal
    return %c : !migraphx.shaped<2x3xf32, 6x2x1>
  }
}

//===----------------------------------------------------------------------===//
// Valid: int non-splat
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @int_non_splat
  func.func @int_non_splat() -> !migraphx.shaped<2x2xi32, 2x1> {
    %c = "migraphx.literal"() {value = dense<[1, 2, 3, 4]> : tensor<2x2xi32>} : () -> !migraphx.shaped<2x2xi32, 2x1>
    // CHECK: migraphx.literal
    return %c : !migraphx.shaped<2x2xi32, 2x1>
  }
}

//===----------------------------------------------------------------------===//
// Valid: bool splat
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @bool_splat
  func.func @bool_splat() -> !migraphx.shaped<4xi1, 1> {
    %c = "migraphx.literal"() {value = dense<true> : tensor<4xi1>} : () -> !migraphx.shaped<4xi1, 1>
    // CHECK: migraphx.literal
    return %c : !migraphx.shaped<4xi1, 1>
  }
}

//===----------------------------------------------------------------------===//
// Invalid: not a shaped type
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @not_shaped_type
  func.func @not_shaped_type() -> f32 {
    // expected-error @+1 {{failed to materialize constant: type is not migraphx.shaped}}
    %c = "migraphx.literal"() {value = dense<1.0> : tensor<f32>} : () -> f32
    return %c : f32
  }
}

//===----------------------------------------------------------------------===//
// Invalid: value is not ElementsAttr
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @not_elements_attr
  func.func @not_elements_attr() -> !migraphx.shaped<2x2xf32, 2x1> {
    // expected-error @+1 {{failed to materialize constant: value is not an ElementsAttr}}
    %c = "migraphx.literal"() {value = 42 : i32} : () -> !migraphx.shaped<2x2xf32, 2x1>
    return %c : !migraphx.shaped<2x2xf32, 2x1>
  }
}

//===----------------------------------------------------------------------===//
// Invalid: shape mismatch (should fail in LiteralOp::verify)
//===----------------------------------------------------------------------===//
module {
  // CHECK-LABEL: func @shape_mismatch
  func.func @shape_mismatch() -> !migraphx.shaped<2x2xf32, 2x1> {
    // expected-error @+1 {{non-splat literals must have a value that matches the literal's logical shape}}
    %c = "migraphx.literal"() {value = dense<[1.0, 2.0, 3.0]> : tensor<3xf32>} : () -> !migraphx.shaped<2x2xf32, 2x1>
    return %c : !migraphx.shaped<2x2xf32, 2x1>
  }
}