//This file is automatically generated. Do not edit!

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_1
// CHECK_Resnext101_f32_7_1: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_1: [1]

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d -fil_layout=gkyxc -in_layout=nhwgc -out_layout=nhwgk -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_2
// CHECK_Resnext101_f32_7_2: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_2: [1]

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d_bwd_data -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_3
// CHECK_Resnext101_f32_7_3: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_3: [1]

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d_bwd_data -fil_layout=gkyxc -in_layout=nhwgc -out_layout=nhwgk -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_4
// CHECK_Resnext101_f32_7_4: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_4: [1]

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d_bwd_weight -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_5
// CHECK_Resnext101_f32_7_5: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_5: [1]

// RUN: miopen-gen -batchsize=64 -groupsize=32 -in_channels=512 -in_h=28 -in_w=28 -out_channels=512 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --conv_stride_h=2 --conv_stride_w=2 --padding_h=1 --padding_w=1 --operation conv2d_bwd_weight -fil_layout=gkyxc -in_layout=nhwgc -out_layout=nhwgk -t f32  %pv %random_data %xdlops | mlir-miopen-driver -c | mlir-rocm-runner --shared-libs=%linalg_test_lib_dir/libmlir_rocm_runtime%shlibext,%rocm_wrapper_library_dir/librocm-runtime-wrappers%shlibext,%linalg_test_lib_dir/libmlir_runner_utils%shlibext --entry-point-result=void | FileCheck %s --check-prefix=CHECK_Resnext101_f32_7_6
// CHECK_Resnext101_f32_7_6: Unranked Memref base@ = 0x{{.*}} rank = 1 offset = 0 sizes = [1] strides = [1] data =
// CHECK_Resnext101_f32_7_6: [1]

