---
# iree-compile flags
- "--iree-global-opt-propagate-transposes=true"
- "--iree-opt-outer-dim-concat=true"
- "--iree-opt-const-eval=false"
- "--iree-opt-data-tiling=false"
- "--iree-rocm-waves-per-eu=2"
- "--iree-vm-target-truncate-unsupported-floats"
- "--iree-codegen-llvmgpu-use-vector-distribution"
- "--iree-llvmgpu-enable-prefetch"
- "--iree-codegen-gpu-native-math-precision=true"
- "--iree-flow-enable-aggressive-fusion"
- "--iree-global-opt-enable-fuse-horizontal-contractions=true"
- "--iree-opt-aggressively-propagate-transposes=true"
- "--iree-execution-model=async-external"
- "--iree-flow-enable-fuse-padding-into-linalg-consumer-ops"
- "--iree-flow-element-wise-fuse-multi-reduction"
- "--iree-flow-enable-fuse-padding-into-linalg-producer-ops"
- "--iree-flow-fuse-multi-use"
