resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - amd-staging
    - amd-mainline-open
  paths:
    exclude:
    - .ci
    - .github
    - '*.md'
    - '**/*.md'
    - LICENSE.TXT

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/llvm-project.yml@pipelines_repo
